apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: greenhouse
    component: greenhouse
    tier: backend
  name: greenhouse
  namespace: greenhouse
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: greenhouse
      component: greenhouse
      tier: backend
  template:
    metadata:
      labels:
        app: greenhouse
        component: greenhouse
        tier: backend
    spec:
      containers:
      - env:
        - name: CACHE_IGNORE
          value: js|html
        - name: CACHE_PUBLIC_EXPIRATION
          value: 3d
        image: docker.io/runzexia/greenhouse:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
        imagePullPolicy: Always
        name: ks-sample
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30